# Minimal Slack API Kubernetes Configuration
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: slack-api
  labels:
    name: slack-api

---
# Deployment (minimal configuration)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-api
  namespace: slack-api
  labels:
    app: slack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-api
  template:
    metadata:
      labels:
        app: slack-api
    spec:
      containers:
      - name: slack-api
        image: sarindockerhub/slack-api:latest  # Update with your actual Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
        # Only include environment variables your app actually needs
        # env:
        # - name: PORT
        #   value: "8181"
        # Add your specific environment variables here
        resources:
          requests:
            memory: "64Mi"   # Very minimal for basic apps
            cpu: "50m"
          limits:
            memory: "128Mi"  # Can increase if needed
            cpu: "100m"
        # Basic health check using the port
        livenessProbe:
          tcpSocket:
            port: 8181
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 5

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: slack-api-service
  namespace: slack-api
spec:
  selector:
    app: slack-api
  ports:
  - port: 80
    targetPort: 8181
  type: NodePort  # Simple external access

